services:
  - type: web
    name: minha-flask-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python populate_data.py || true
      gunicorn app:app -b 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PORT
        fromService:
          type: web
          name: minha-flask-app
          property: port